-- MySQL Script generated by MySQL Workbench
-- lun 17 may 2021 07:36:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema prep
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prep` DEFAULT CHARACTER SET utf8 ;

USE `prep` ;
-- -----------------------------------------------------
-- Schema prep
-- -----------------------------------------------------
-- Table `prep`.`CANDIDATURAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prep`.`CANDIDATURAS` (
  `candidaturas_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_candidatura` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`candidaturas_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PARTIDOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prep`.`PARTIDOS` (
  `partido_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `alianza` VARCHAR(45) NULL,
  `no_votos` INT NULL DEFAULT 0,
  `fk_alianza_id` INT NULL,
  PRIMARY KEY (`partido_id`),
  INDEX `fk_PARTIDOS_ALIANZAS1_idx` (`fk_alianza_id` ASC) VISIBLE,
  CONSTRAINT `fk_PARTIDOS_ALIANZAS1`
    FOREIGN KEY (`fk_alianza_id`)
    REFERENCES `prep`.`ALIANZAS` (`alianza_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REGISTROS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prep`.`REGISTROS` (
  `registro_id` INT NOT NULL AUTO_INCREMENT,
  `fk_partido_id` INT NOT NULL,
  `fk_casilla_id` INT NOT NULL,
  `candidatura` VARCHAR(45) NULL,
  `fk_candidato_id` INT NOT NULL,
  PRIMARY KEY (`registro_id`),
  INDEX `fk_REGISTROS_PARTIDOS_idx` (`fk_partido_id` ASC) VISIBLE,
  INDEX `fk_REGISTROS_CASILLAS1_idx` (`fk_casilla_id` ASC) VISIBLE,
  INDEX `fk_REGISTROS_CANDIDATOS1_idx` (`fk_candidato_id` ASC) VISIBLE,
  CONSTRAINT `fk_REGISTROS_PARTIDOS`
    FOREIGN KEY (`fk_partido_id`)
    REFERENCES `mydb`.`PARTIDOS` (`partido_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_REGISTROS_CASILLAS1`
    FOREIGN KEY (`fk_casilla_id`)
    REFERENCES `prep`.`CASILLAS` (`casilla_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_REGISTROS_CANDIDATOS1`
    FOREIGN KEY (`fk_candidato_id`)
    REFERENCES `prep`.`CANDIDATOS` (`candidato_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prep`.`USUARIOS` (
  `usuario` VARCHAR(20) NOT NULL COMMENT '		',
  `email` VARCHAR(45) NOT NULL,
  `tipo_usuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `numero_telefono` VARCHAR(10) NOT NULL,
  `red_social` VARCHAR(45) NULL DEFAULT NULL,
  `DOMICILIO_domicilio_id` INT NOT NULL,
  PRIMARY KEY (`usuario`),
  INDEX `fk_USUARIOS_DOMICILIO1_idx` (`DOMICILIO_domicilio_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prep`.`ALIANZAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prep`.`ALIANZAS` (
  `alianza_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `no_votos` INT NOT NULL,
  PRIMARY KEY (`alianza_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prep`.`CANDIDATOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prep`.`CANDIDATOS` (
  `candidato_id` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NULL,
  `fk_domicilio_id` INT NOT NULL,
  PRIMARY KEY (`candidato_id`),
  INDEX `fk_CANDIDATOS_DOMICILIO1_idx` (`fk_domicilio_id` ASC) VISIBLE,
  CONSTRAINT `fk_CANDIDATOS_DOMICILIO1`
    FOREIGN KEY (`fk_domicilio_id`)
    REFERENCES `prep`.`DOMICILIOS` (`domicilio_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prep`.`CANDIDATURAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prep`.`CANDIDATURAS` (
  `candidatura_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_candidatura` VARCHAR(45) NULL,
  PRIMARY KEY (`candidatura_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prep`.`CANDIDATURAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prep`.`CANDIDATURAS` (
  `candidatura_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_candidatura` VARCHAR(45) NULL,
  PRIMARY KEY (`candidatura_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prep`.`CASILLAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prep`.`CASILLAS` (
  `casilla_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_casilla` VARCHAR(45) NULL,
  `fk_seccion` INT NOT NULL,
  PRIMARY KEY (`casilla_id`),
  INDEX `fk_CASILLAS_SECCIONALES_idx` (`fk_seccion` ASC) VISIBLE,
  CONSTRAINT `fk_CASILLAS_SECCIONALES`
    FOREIGN KEY (`fk_seccion`)
    REFERENCES `prep`.`SECCIONALES` (`seccion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prep`.`DOMICILIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prep`.`DOMICILIOS` (
  `domicilio_id` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NOT NULL,
  `colonia` VARCHAR(45) NOT NULL,
  `cp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`domicilio_id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `prep`.`SECCIONALES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prep`.`SECCIONALES` (
  `seccion` INT NOT NULL AUTO_INCREMENT,
  `entidad` VARCHAR(45) NULL,
  `distrito` VARCHAR(45) NULL,
  PRIMARY KEY (`seccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prep`.`table2`
-- -----------------------------------------------------

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
