-- MySQL Script generated by MySQL Workbench
-- jue 27 may 2021 10:56:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- ----------------------------------------------------
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prep` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;


USE `prep` ;
CREATE TABLE IF NOT EXISTS `prep`.`domicilios` (
  `domicilio_id` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NOT NULL,
  `colonia` VARCHAR(45) NOT NULL,
  `cp` VARCHAR(45) NOT NULL,
  `usuarios_usuarios_id` INT NOT NULL,
  PRIMARY KEY (`domicilio_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


CREATE TABLE IF NOT EXISTS `prep`.`seccionales` (
  `seccion` INT NOT NULL AUTO_INCREMENT,
  `entidad` VARCHAR(45) NULL DEFAULT NULL,
  `distrito` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`seccion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prep`.`alianzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prep`.`alianzas` (
  `alianza_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `no_votos` INT NOT NULL,
  PRIMARY KEY (`alianza_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `prep`.`partidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prep`.`partidos` (
  `partido_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `no_votos` INT NOT NULL,
  `alianza_id` INT NOT NULL,
  PRIMARY KEY (`partido_id`),
  INDEX `fk_partidos_ALIANZAS1_idx` (`alianza_id` ASC) VISIBLE,
  CONSTRAINT `fk_partidos_ALIANZAS1`
    FOREIGN KEY (`alianza_id`)
    REFERENCES `prep`.`alianzas` (`alianza_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prep`.`candidatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prep`.`candidatos` (
  `candidato_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `domicilio_id` INT NOT NULL,
  `partido_id` INT NOT NULL,
  PRIMARY KEY (`candidato_id`),
  INDEX `fk_CANDIDATOS_DOMICILIO1_idx` (`domicilio_id` ASC) VISIBLE,
  INDEX `fk_candidatos_partidos1_idx` (`partido_id` ASC) VISIBLE,
  CONSTRAINT `fk_CANDIDATOS_DOMICILIO1`
    FOREIGN KEY (`domicilio_id`)
    REFERENCES `prep`.`domicilios` (`domicilio_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_candidatos_partidos1`
    FOREIGN KEY (`partido_id`)
    REFERENCES `prep`.`partidos` (`partido_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `prep`.`casillas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prep`.`casillas` (
  `casilla_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_casilla` VARCHAR(45) NULL DEFAULT NULL,
  `seccion` INT NOT NULL,
  PRIMARY KEY (`casilla_id`),
  INDEX `fk_CASILLAS_SECCIONALES_idx` (`seccion` ASC) VISIBLE,
  CONSTRAINT `fk_CASILLAS_SECCIONALES`
    FOREIGN KEY (`seccion`)
    REFERENCES `prep`.`seccionales` (`seccion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `prep`.`registros` (
  `registro_id` INT NOT NULL AUTO_INCREMENT,
  `candidatura` VARCHAR(45) NULL DEFAULT NULL,
  `casilla_id` INT NOT NULL,
  `candidato_id` INT NOT NULL,
  `partido_id` INT NOT NULL,
  PRIMARY KEY (`registro_id`),
  INDEX `fk_REGISTROS_CASILLAS1_idx` (`casilla_id` ASC) VISIBLE,
  INDEX `fk_REGISTROS_CANDIDATOS1_idx` (`candidato_id` ASC) VISIBLE,
  INDEX `fk_registros_partidos1_idx` (`partido_id` ASC) VISIBLE,
  CONSTRAINT `fk_REGISTROS_CANDIDATOS1`
    FOREIGN KEY (`candidato_id`)
    REFERENCES `prep`.`candidatos` (`candidato_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_REGISTROS_CASILLAS1`
    FOREIGN KEY (`casilla_id`)
    REFERENCES `prep`.`casillas` (`casilla_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_registros_partidos1`
    FOREIGN KEY (`partido_id`)
    REFERENCES `prep`.`partidos` (`partido_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


CREATE TABLE IF NOT EXISTS `prep`.`usuarios` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `no_telefono` VARCHAR(45) NULL,
  `red_social` VARCHAR(45) NULL,
  `domicilio_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`),
  INDEX `fk_usuarios_DOMICILIOS1_idx` (`domicilio_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_DOMICILIOS1`
    FOREIGN KEY (`domicilio_id`)
    REFERENCES `prep`.`domicilios` (`domicilio_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

