-- MySQL Script generated by MySQL Workbench
-- jue 27 may 2021 10:56:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
DROP DATABASE IF EXISTS prep;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- ----------------------------------------------------
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prep` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `prep` ;

CREATE TABLE IF NOT EXISTS `prep`.`candidaturas` (
  `candidatura_id` INT NOT NULL AUTO_INCREMENT,
  `puesto` VARCHAR(45) NOT NULL,
  `municipio` VARCHAR(45),
  `distrito` INT,  
  Primary key (`candidatura_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `prep`.`partidos` (
  `partido_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `alianza` VARCHAR(45),
  PRIMARY KEY (`partido_id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `prep`.`candidatos` (
  `candidato_id` INT NOT NULL AUTO_INCREMENT,
  `candidatura_id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `partido_id` INT NOT NULL,
  PRIMARY KEY (`candidato_id`),
  INDEX `fk_candidatos_partidos1_idx` (`partido_id` ASC) VISIBLE,
  CONSTRAINT `fk_candidatos_partidos1`
    FOREIGN KEY (`partido_id`)
    REFERENCES `prep`.`partidos` (`partido_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (`candidatura_id`)
    REFERENCES `prep`.`candidaturas` (`candidatura_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `prep`.`casillas` (
  `casilla_id` INT NOT NULL,
  `numero_casilla` INT,
  `seccion` INT,
  `tipo_casilla` VARCHAR(45),
  PRIMARY KEY (`casilla_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `prep`.`registros` (
  `registro_id` INT NOT NULL AUTO_INCREMENT,
  `candidatura_id` INT,
  `partido_id` INT,
  `no_votos` INT,
  `casilla_id` INT,
  PRIMARY KEY (`registro_id`),
  FOREIGN KEY (`casilla_id`)
  REFERENCES `prep`.`casillas` (`casilla_id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,  
  FOREIGN KEY (`candidatura_id`)
  REFERENCES `prep`.`candidaturas` (`candidatura_id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,  
  FOREIGN KEY (`partido_id`)
  REFERENCES `prep`.`partidos` (`partido_id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `prep`.`usuarios` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario` VARCHAR(45) ,
  `nombre` VARCHAR(45) ,
  `apellido` VARCHAR(45),
  `email` VARCHAR(45),
  `contraseña` VARCHAR(45),
  `no_telefono` VARCHAR(45),
  `red_social` VARCHAR(45),
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


CREATE TABLE IF NOT EXISTS `prep`.`domicilios` (
  `domicilio_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(20), 
  `colonia` VARCHAR(45),
  `cp` VARCHAR(10),
  PRIMARY KEY (`domicilio_id`),
  FOREIGN KEY (`usuario_id`)
    REFERENCES `prep`.`usuarios` (`usuario_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

